/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.apng;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.AsyncResult;
import org.appcelerator.kroll.common.TiMessenger;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;
import android.os.Message;

import ti.modules.titanium.ui.UIModule;
import ti.modules.titanium.ui.widget.TiUIImageView;

@Kroll.proxy(creatableInModule=TiApngModule.class,
		propertyAccessors = {
				TiC.PROPERTY_IMAGE,
		})

public class ImageViewProxy extends TiViewProxy
{
	static final int MSG_START_ANIMATION = KrollProxy.MSG_LAST_ID + 101;
	static final int MSG_STOP_ANIMATION = KrollProxy.MSG_LAST_ID + 102;

	// Constructor
	public ImageViewProxy()
	{
		super();
	}

	protected ApngImageView getView()
	{
		return (ApngImageView) getOrCreateView();
	}

	@Override
	public TiUIView createView(Activity activity)
	{
		TiUIView view = new ApngImageView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	public boolean handleMessage(Message message)
	{
		AsyncResult result = null;
		switch (message.what) {
			case MSG_START_ANIMATION: {
				result = (AsyncResult) message.obj;
				getView().start();
				result.setResult(null);
				return true;
			}

			case MSG_STOP_ANIMATION: {
				getView().start();
				result.setResult(null);
				return true;
			}
		}

		return super.handleMessage(message);
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options)
	{
		super.handleCreationDict(options);
	}

	@Kroll.method
	public void stop()
	{
		if (TiApplication.isUIThread()) {
			getView().stop();
		} else {
			TiMessenger.sendBlockingMainMessage(getMainHandler().obtainMessage(MSG_STOP_ANIMATION));
		}
	}

	@Kroll.method
	public void start()
	{
		if (TiApplication.isUIThread()) {
			getView().start();
		} else {
			TiMessenger.sendBlockingMainMessage(getMainHandler().obtainMessage(MSG_START_ANIMATION));
		}
	}

	@Kroll.getProperty
	public boolean playing()
	{
		return getView().isPlaying;
	}
}
